### PR TITLE
Added many more things in the website

### PR DESCRIPTION
**Pull request by agam778**
Added dynamic favicon (adjusted automatically for different platforms), added MetaData (preview when sending links like in discord, linkedin, etc. also added the new icon in the website instead of the old one. @axtloss @jaasio 

Preview

Screenshot from 2021-07-23 10-37-27

### CODE REVIEW

**Comment by agam778** [comment]
Even preview in discord

image

**Comment by axtloss** [comment]
We aren't updating the placeholder website, but focussing on the (future) main website instead

**Comment by agam778** [comment]
Ok, but you can use this code in your future website to not code these things again! @axtloss

**Comment by nickdotzip** [comment]
> Ok, but you can use this code in your future website to not code these things again! @axtloss

thank you, agam

**Pull request closed without merging**
